### ISSUE TITLE
Feature request: allow option to specify an interface to attack

### ISSUE THREAD

**Issue by LukeWilladsen** [DanMcInerney/icebreaker#1]
Very cool tool! Just having this one minor issue.

I am specifying a host list that has only targets that can be reached via eth1 on my machine, but it is starting responder to only listen on eth0. I don't have the option of specifying which interface I want.

`    [Responder] 01/22/2018 03:44:02 PM - Responder Started:  ['submodules/Responder/Responder.py', '-wrd', '-I', 'eth0']`

**Comment by DanMcInerney** [comment]
Ah, yeah, my interface detection is weak at the moment. I'll fix this soon.
If you want to manually bypass this for the moment you can edit line 725
and line 735 from *iface = get_iface()* to *iface = "eth1"*

**Comment by DanMcInerney** [comment]
Done. -i  <interface name> option will work now.
