### ISSUE TITLE
RID Fails

### ISSUE THREAD

**Issue by bucky67gto** [DanMcInerney/icebreaker#11]
If I exclude the rid we are good, but if i do the default, I get:

*] Attack 1: RID cycling in null SMB sessions into reverse bruteforce
[*] Checking for null SMB sessions
[*] Example command that will run: rpcclient -U "" 10.207.4.3 -N -c "lsaquery"
Traceback (most recent call last):
  File "./icebreaker.py", line 1536, in <module>
    main(report, args)
  File "./icebreaker.py", line 1472, in main
    prev_creds, prev_users, domains = smb_reverse_brute(loop, hosts, args, passwords, prev_creds, prev_users, DCs)
  File "./icebreaker.py", line 589, in smb_reverse_brute
    null_sess_hosts = get_null_sess_hosts(rpc_output)
  File "./icebreaker.py", line 399, in get_null_sess_hosts
    if 'Domain Name:' in out:
TypeError: argument of type 'NoneType' is not iterable

Thoughts????

**Comment by skorov** [comment]
I get the same problem.

This should fix it: (line 399)
`if out and 'Domain Name:' in out:`

**Comment by DanMcInerney** [comment]
Can you show me the output of logs/rpcclient.log?

**Comment by DanMcInerney** [comment]
I fixed this like @skorov did. I think I know what was happening.
