### ISSUE TITLE
nmap XML input is broken

### ISSUE THREAD

**Issue by AbstractClass** [DanMcInerney/icebreaker#7]
The function `run_nse_scripts` declares a positional argument `hosts` then immediately overwrites it with `hosts = []`, throwing an index error.  If this is fixed, another issue arises: `TypeError: sequence item 0: expected str instance, NmapHost found` stemming from line 133 (`report = NmapScan(hosts)`) in icebreaker.py, I assume this is because the list of hosts passed to the function on line 1457 contains a list of NmapHost objects, not a list of IPs in str format.

**Comment by DanMcInerney** [comment]
Yeah, you right. Fixing.

**Comment by DanMcInerney** [comment]
Fixed
